openapi: 3.0.1
info:
  description: ""
  title: Deals
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "When a sales rep is negotiating a potential purchase with\
    \ a prospective customer, create a deal record to track the negotiation process.\
    \ When the customer later makes their purchase, you can update the deal to a closed\
    \ stage."
  x-hubspot-related-documentation:
  - name: Deals Guide
    url: https://hubspot.dev/guides/api/crm/deals
  x-hubspot-introduction: "Use the deals API to create and manage CRM records that\
    \ represent transactions with contacts and/or companies. Deals progress through\
    \ pipeline stages to reflect whether the transaction has been completed, is active,\
    \ or has otherwise been lost."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Public_Object
- name: Associations
- name: GDPR
- name: Search
paths:
  /crm/v3/objects/deals/batch/read:
    post:
      operationId: BatchRead
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      summary: "Read a batch of deals by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/deals/{dealId}:
    delete:
      description: "Move an Object identified by `{dealId}` to the recycling bin."
      operationId: Archive
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{dealId}`. `{dealId}` refers to\
        \ the internal object ID by default, or optionally any unique property value\
        \ as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: GetByID
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{dealId}`.\
        \ `{dealId}` refers to the internal object ID by default, or optionally any\
        \ unique property value as specified by the `idProperty` query param. Provided\
        \ property values will be overwritten. Read-only and non-existent properties\
        \ will be ignored. Properties values can be cleared by passing an empty string."
      operationId: Update
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/deals/merge:
    post:
      operationId: Merge
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Merge two deals with same type
      tags:
      - Public_Object
  /crm/v3/objects/deals/batch/archive:
    post:
      operationId: BatchArchive
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Archive a batch of deals by ID
      tags:
      - Batch
  /crm/v3/objects/deals/batch/create:
    post:
      operationId: BatchCreate
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Create a batch of deals
      tags:
      - Batch
  /crm/v3/objects/deals/batch/update:
    post:
      operationId: BatchUpdate
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Update a batch of deals
      tags:
      - Batch
  /crm/v3/objects/deals/gdpr-delete:
    post:
      description: "Permanently delete a contact and all associated content to follow\
        \ GDPR. Use optional property 'idProperty' set to 'email' to identify contact\
        \ by email address. If email address is not found, the email address will\
        \ be added to a blocklist and prevent it from being used in the future."
      operationId: post-/crm/v3/objects/deals/gdpr-delete_purge
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: GDPR DELETE
      tags:
      - GDPR
  /crm/v3/objects/deals:
    get:
      description: Read a page of deals. Control what is returned via the `properties`
        query param.
      operationId: GetPage
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      summary: List
      tags:
      - Basic
    post:
      description: "Create a deal with the given properties and return a copy of the\
        \ object, including the ID. Documentation and examples for creating standard\
        \ deals is provided."
      operationId: Create
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/deals/search:
    post:
      operationId: Search
      security:
      - oauth2:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.deals.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            media_bridge.read: Read media and media events
            crm.objects.goals.read: Read goals
            tickets: Read and write tickets
            crm.objects.custom.read: View custom object records
            e-commerce: e-commerce
            crm.objects.custom.write: Change custom object records
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.deals.read: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.deals.write: ' '
            crm.objects.quotes.read: Quotes
            crm.objects.line_items.write: Line Items
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.contacts.write: ' '
            crm.objects.contacts.read: ' '
            crm.objects.quotes.write: Quotes
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
