openapi: 3.0.1
info:
  description: All HubSpot objects store data in default and custom properties. These
    endpoints provide access to read and modify object properties in HubSpot.
  title: Properties
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Core
- name: Batch
- name: Groups
paths:
  /crm/v3/properties/{objectType}:
    get:
      description: Read all existing properties for the specified object type and
        HubSpot account.
      operationId: get-/crm/v3/properties/{objectType}_getAll
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      summary: Read all properties
      tags:
      - Core
    post:
      description: Create and return a copy of a new property for the specified object
        type.
      operationId: post-/crm/v3/properties/{objectType}_create
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Create a property
      tags:
      - Core
  /crm/v3/properties/{objectType}/batch/archive:
    post:
      description: Archive a provided list of properties. This method will return
        a 204 No Content response on success regardless of the initial state of the
        property (e.g. active, already archived, non-existent).
      operationId: post-/crm/v3/properties/{objectType}/batch/archive_archive
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Archive a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/batch/create:
    post:
      description: Create a batch of properties using the same rules as when creating
        an individual property.
      operationId: post-/crm/v3/properties/{objectType}/batch/create_create
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Create a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/batch/read:
    post:
      description: Read a provided list of properties.
      operationId: post-/crm/v3/properties/{objectType}/batch/read_read
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      summary: Read a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/groups:
    get:
      description: Read all existing property groups for the specified object type
        and HubSpot account.
      operationId: get-/crm/v3/properties/{objectType}/groups_getAll
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      summary: Read all property groups
      tags:
      - Groups
    post:
      description: Create and return a copy of a new property group.
      operationId: post-/crm/v3/properties/{objectType}/groups_create
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Create a property group
      tags:
      - Groups
  /crm/v3/properties/{objectType}/groups/{groupName}:
    delete:
      description: Move a property group identified by {groupName} to the recycling
        bin.
      operationId: delete-/crm/v3/properties/{objectType}/groups/{groupName}_archive
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Archive a property group
      tags:
      - Groups
    get:
      description: Read a property group identified by {groupName}.
      operationId: get-/crm/v3/properties/{objectType}/groups/{groupName}_getByName
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      summary: Read a property group
      tags:
      - Groups
    patch:
      description: Perform a partial update of a property group identified by {groupName}.
        Provided fields will be overwritten.
      operationId: patch-/crm/v3/properties/{objectType}/groups/{groupName}_update
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Update a property group
      tags:
      - Groups
  /crm/v3/properties/{objectType}/{propertyName}:
    delete:
      description: Move a property identified by {propertyName} to the recycling bin.
      operationId: delete-/crm/v3/properties/{objectType}/{propertyName}_archive
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Archive a property
      tags:
      - Core
    get:
      description: Read a property identified by {propertyName}.
      operationId: get-/crm/v3/properties/{objectType}/{propertyName}_getByName
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      summary: Read a property
      tags:
      - Core
    patch:
      description: Perform a partial update of a property identified by {propertyName}.
        Provided fields will be overwritten.
      operationId: patch-/crm/v3/properties/{objectType}/{propertyName}_update
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Update a property
      tags:
      - Core
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            timeline: Create timeline events
            e-commerce: e-commerce
            contacts: Read from and write to my Contacts
            media_bridge.read: Read media and media events
            tickets: Read and write tickets
            crm.schemas.custom.read: View custom object definitions
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.companies.read: ' '
            crm.objects.deals.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.contacts.write: ' '
            crm.schemas.deals.read: ' '
            crm.objects.contacts.read: ' '
            crm.objects.deals.write: ' '
            crm.schemas.contacts.read: ' '
            crm.schemas.companies.read: ' '
            crm.schemas.contacts.write: ' '
            crm.schemas.deals.write: ' '
            crm.schemas.companies.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
