openapi: 3.0.1
info:
  title: Domains
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- description: Operations for fetching domains
  name: Domains
paths:
  /cms/v3/domains/:
    get:
      description: Returns all existing domains that have been created. Results can
        be limited and filtered by creation or updated date.
      operationId: GetPage
      security:
      - private_apps_legacy:
        - content
      - oauth2:
        - cms.domains.read
      - private_apps:
        - cms.domains.read
      - private_apps:
        - cms.domains.write
      - oauth2:
        - cms.domains.write
      - private_apps_legacy:
        - cms.knowledge_base.settings.write
      - oauth2_legacy:
        - cms.knowledge_base.settings.write
      - oauth2_legacy:
        - content
      summary: Get current domains
      tags:
      - Domains
  /cms/v3/domains/{domainId}:
    get:
      description: Returns a single domains with the id specified.
      operationId: GetByID
      security:
      - private_apps_legacy:
        - content
      - oauth2:
        - cms.domains.read
      - private_apps:
        - cms.domains.read
      - private_apps:
        - cms.domains.write
      - oauth2:
        - cms.domains.write
      - private_apps_legacy:
        - cms.knowledge_base.settings.write
      - oauth2_legacy:
        - cms.knowledge_base.settings.write
      - oauth2_legacy:
        - content
      summary: Get a single domain
      tags:
      - Domains
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            cms.knowledge_base.settings.write: Update knowledge base settings
            content: Read from and write to my Content
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            cms.domains.write: Create or update domains.
            cms.domains.read: Read domains.
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
