openapi: 3.0.1
info:
  title: CrmPublicAssociationsServiceV4
  version: v4
servers:
- url: https://api.hubapi.com/
tags:
- name: Batch
- name: Definitions
paths:
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive:
    post:
      description: Batch delete associations for objects
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive_archive"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Delete
      tags:
      - Batch
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default:
    post:
      description: Create the default (most generic) association type between two
        object types
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default_createDefault"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: ' Create Default Associations'
      tags:
      - Batch
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create:
    post:
      description: Batch create associations for objects
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create_create"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Create
      tags:
      - Batch
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive:
    post:
      description: Batch delete specific association labels for objects. Deleting
        an unlabeled association will also delete all labeled associations between
        those two objects
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive_archiveLabels"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Delete Specific Labels
      tags:
      - Batch
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read:
    post:
      description: 'Batch read associations for objects to specific object type. The
        ''after'' field in a returned paging object  can be added alongside the ''id''
        to retrieve the next page of associations from that objectId. The ''link''
        field is deprecated and should be ignored. '
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read_getPage"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Read
      tags:
      - Batch
  /crm/v4/associations/{fromObjectType}/{toObjectType}/labels:
    get:
      description: Returns all association types between two object types
      operationId: "get-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_getAll"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Read
      tags:
      - Definitions
    post:
      description: Create a user defined association definition
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_create"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Create
      tags:
      - Definitions
    put:
      description: Update a user defined association definition
      operationId: "put-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels_update"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Update
      tags:
      - Definitions
  /crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}:
    delete:
      description: Deletes an association definition
      operationId: "delete-/crm/v4/associations/{fromObjectType}/{toObjectType}/labels/{associationTypeId}_archive"
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - crm.objects.custom.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - private_apps:
        - crm.objects.quotes.read
      summary: Delete
      tags:
      - Definitions
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            e-commerce: e-commerce
            crm.objects.custom.write: Change custom object records
            crm.objects.custom.read: View custom object records
            crm.objects.goals.read: Read goals
            tickets: Read and write tickets
            media_bridge.read: Read media and media events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.quotes.read: Quotes
            crm.objects.line_items.write: Line Items
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.contacts.write: ' '
            crm.objects.contacts.read: ' '
            crm.objects.quotes.write: Quotes
            crm.objects.deals.read: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.deals.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
