openapi: 3.0.1
info:
  description: "Pipelines represent distinct stages in a workflow, like closing a\
    \ deal or servicing a support ticket. These endpoints provide access to read and\
    \ modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object\
    \ types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId\
    \ as a parameter, that ID must correspond to an existing, un-archived pipeline.\
    \ Otherwise the request will fail with a `404 Not Found` response."
  title: Pipelines
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "To streamline customer support processes, use this API\
    \ to retrieve your existing ticket pipelines and add new stages based on your\
    \ business needs. Support reps can then assign tickets to those pipeline stages\
    \ to track progress on customer issues."
  x-hubspot-related-documentation:
  - name: Pipelines Guide
    url: https://hubspot.dev/guides/api/crm/pipelines
  x-hubspot-introduction: "Use the pipelines API to create and manage deal and ticket\
    \ pipelines. Pipelines enable you to track the status or progress of deals and\
    \ tickets, such as closing deals and opening support tickets."
servers:
- url: https://api.hubapi.com
tags:
- description: ""
  name: Pipeline Stage Audits
  x-hubspot-tag-name-english-source: Pipeline Stage Audits
- description: ""
  name: Pipelines
  x-hubspot-tag-name-english-source: Pipelines
- description: ""
  name: Pipeline Audits
  x-hubspot-tag-name-english-source: Pipeline Audits
- description: ""
  name: Pipeline Stages
  x-hubspot-tag-name-english-source: Pipeline Stages
paths:
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit:
    get:
      description: "Return a reverse chronological list of all mutations that have\
        \ occurred on the pipeline stage identified by `{stageId}`."
      operationId: StagesGetAudit
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return an audit of all changes to the pipeline stage
      tags:
      - Pipeline Stage Audits
  /crm/v3/pipelines/{objectType}/{pipelineId}:
    delete:
      description: "Delete the pipeline identified by `{pipelineId}`."
      operationId: Archive
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Delete a pipeline
      tags:
      - Pipelines
    get:
      description: "Return a single pipeline object identified by its unique `{pipelineId}`."
      operationId: GetByID
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return a pipeline by ID
      tags:
      - Pipelines
    patch:
      description: "Perform a partial update of the pipeline identified by `{pipelineId}`.\
        \ The updated pipeline will be returned in the response."
      operationId: Update
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a pipeline
      tags:
      - Pipelines
    put:
      description: Replace all the properties of an existing pipeline with the values
        provided. This will overwrite any existing pipeline stages. The updated pipeline
        will be returned in the response.
      operationId: Replace
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Replace a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}/audit:
    get:
      description: "Return a reverse chronological list of all mutations that have\
        \ occurred on the pipeline identified by `{pipelineId}`."
      operationId: GetAudit
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return an audit of all changes to the pipeline
      tags:
      - Pipeline Audits
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages:
    get:
      description: "Return all the stages associated with the pipeline identified\
        \ by `{pipelineId}`."
      operationId: StagesGetAll
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return all stages of a pipeline
      tags:
      - Pipeline Stages
    post:
      description: "Create a new stage associated with the pipeline identified by\
        \ `{pipelineId}`. The entire stage object, including its unique ID, will be\
        \ returned in the response."
      operationId: StagesCreate
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a pipeline stage
      tags:
      - Pipeline Stages
  /crm/v3/pipelines/{objectType}:
    get:
      description: "Return all pipelines for the object type specified by `{objectType}`."
      operationId: GetAll
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Retrieve all pipelines
      tags:
      - Pipelines
    post:
      description: "Create a new pipeline with the provided property values. The entire\
        \ pipeline object, including its unique ID, will be returned in the response."
      operationId: Create
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}:
    delete:
      description: "Delete the pipeline stage identified by `{stageId}` associated\
        \ with the pipeline identified by `{pipelineId}`."
      operationId: StagesArchive
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Delete a pipeline stage
      tags:
      - Pipeline Stages
    get:
      description: "Return the stage identified by `{stageId}` associated with the\
        \ pipeline identified by `{pipelineId}`."
      operationId: StagesGetByID
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return a pipeline stage by ID
      tags:
      - Pipeline Stages
    patch:
      description: "Perform a partial update of the pipeline stage identified by `{stageId}`\
        \ associated with the pipeline identified by `{pipelineId}`. Any properties\
        \ not included in this update will keep their existing values. The updated\
        \ stage will be returned in the response."
      operationId: StagesUpdate
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a pipeline stage
      tags:
      - Pipeline Stages
    put:
      description: Replace all the properties of an existing pipeline stage with the
        values provided. The updated stage will be returned in the response.
      operationId: StagesReplace
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Replace a pipeline stage
      tags:
      - Pipeline Stages
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.goals.read: Read goals
            media_bridge.read: Read media and media events
            e-commerce: e-commerce
            timeline: Create timeline events
            crm.schemas.custom.read: View custom object definitions
            tickets: Read and write tickets
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.deals.write: ' '
            crm.schemas.deals.read: ' '
            crm.objects.contacts.read: ' '
            crm.schemas.quotes.read: Quotes schemas
            crm.objects.contacts.write: ' '
            crm.schemas.contacts.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.companies.read: ' '
            crm.schemas.companies.read: ' '
            crm.objects.deals.read: ' '
            crm.schemas.line_items.read: Line Items schemas
            crm.schemas.deals.write: ' '
            crm.schemas.contacts.write: ' '
            crm.schemas.companies.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
x-hubspot-documentation-banner: NONE
