openapi: 3.0.1
info:
  description: "These APIs allow you to interact with HubSpot's Marketing Events Extension.\
    \ It allows you to:\n* Create, Read or update Marketing Event information in HubSpot\n\
    * Specify whether a HubSpot contact has registered, attended or cancelled a registration\
    \ to a Marketing Event.\n* Specify a URL that can be called to get the details\
    \ of a Marketing Event.\n"
  title: Marketing Events Extension
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- description: Operations to interact with URL settings for an external application.
  name: Settings
- description: Endpoints that allow you to create or modify the state of an individual
    Marketing Event in HubSpot.
  name: Basic
- description: Endpoints that allow you to create or modify the state of multiple
    Marketing Events in HubSpot.
  name: Batch
- description: Endpoints that allow you to search for Marketing Events in HubSpot.
  name: Search
- description: "Operations to mark HubSpot contacts as registered, attended or cancelled\
    \ a registration to a Marketing Event."
  name: Subscriber State Changes
paths:
  /marketing/v3/marketing-events/events:
    post:
      description: Creates a new marketing event in HubSpot
      operationId: post-/marketing/v3/marketing-events/events_create
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create a marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/events/delete:
    post:
      description: Bulk delete a number of marketing events in HubSpot
      operationId: post-/marketing/v3/marketing-events/events/delete_archive
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Delete multiple marketing events
      tags:
      - Batch
  /marketing/v3/marketing-events/events/search:
    get:
      description: Search for marketing events that have an event id that starts with
        the query string
      operationId: get-/marketing/v3/marketing-events/events/search_doSearch
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      summary: Search for marketing events
      tags:
      - Search
  /marketing/v3/marketing-events/events/upsert:
    post:
      description: "Upset multiple Marketing Event. If there is an existing Marketing\
        \ event with the specified id, it will be updated; otherwise a new event will\
        \ be created."
      operationId: post-/marketing/v3/marketing-events/events/upsert_doUpsert
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create or update multiple marketing events
      tags:
      - Batch
  /marketing/v3/marketing-events/events/{externalEventId}:
    delete:
      description: "Deletes an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Delete a marketing event
      tags:
      - Basic
    get:
      description: "Returns the details of the Marketing Event with the specified\
        \ id, if one exists."
      operationId: "get-/marketing/v3/marketing-events/events/{externalEventId}_getById"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      summary: Get a marketing event
      tags:
      - Basic
    patch:
      description: "Updates an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: "patch-/marketing/v3/marketing-events/events/{externalEventId}_update"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Update a marketing event
      tags:
      - Basic
    put:
      description: "Upsets a Marketing Event. If there is an existing Marketing event\
        \ with the specified id, it will be updated; otherwise a new event will be\
        \ created."
      operationId: "put-/marketing/v3/marketing-events/events/{externalEventId}_replace"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create or update a marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      description: Mark a marketing event as cancelled.
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_doCancel"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Mark a marketing event as cancelled
      tags:
      - Basic
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses."
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_doEmailUpsertById"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Subscriber State Changes
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids."
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_doUpsertById"
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Subscriber State Changes
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      description: Retrieve the current settings for the application.
      operationId: "get-/marketing/v3/marketing-events/{appId}/settings_getAll"
      security:
      - developer_hapikey: []
      summary: Retrieve the application settings
      tags:
      - Settings
    post:
      description: Create or update the current settings for the application.
      operationId: "post-/marketing/v3/marketing-events/{appId}/settings_create"
      security:
      - developer_hapikey: []
      summary: Update the application settings
      tags:
      - Settings
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.write: Write marketing events
            crm.objects.marketing_events.read: Read marketing events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
