openapi: 3.0.1
info:
  title: Marketing Events Extension
  description: "These APIs allow you to interact with HubSpot's Marketing Events Extension.\
    \ It allows you to:\n* Create, Read or update Marketing Event information in HubSpot\n\
    * Specify whether a HubSpot contact has registered, attended or cancelled a registration\
    \ to a Marketing Event.\n* Specify a URL that can be called to get the details\
    \ of a Marketing Event.\n"
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Settings
  description: Operations to interact with URL settings for an external application.
- name: Basic
  description: Endpoints that allow you to create or modify the state of an individual
    Marketing Event in HubSpot.
- name: Batch
  description: Endpoints that allow you to create or modify the state of multiple
    Marketing Events in HubSpot.
- name: Search
  description: Endpoints that allow you to search for Marketing Events in HubSpot.
- name: Subscriber State Changes
  description: "Operations to mark HubSpot contacts as registered, attended or cancelled\
    \ a registration to a Marketing Event."
paths:
  /marketing/v3/marketing-events/events:
    post:
      tags:
      - Basic
      summary: Create a marketing event
      description: Creates a new marketing event in HubSpot
      operationId: post-/marketing/v3/marketing-events/events
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/delete:
    post:
      tags:
      - Batch
      summary: Delete multiple marketing events
      description: Bulk delete a number of marketing events in HubSpot
      operationId: post-/marketing/v3/marketing-events/events/delete
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/search:
    get:
      tags:
      - Search
      summary: Search for marketing events
      description: Search for marketing events that have an event id that starts with
        the query string
      operationId: get-/marketing/v3/marketing-events/events/search
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.read
  /marketing/v3/marketing-events/events/upsert:
    post:
      tags:
      - Batch
      summary: Create or update multiple marketing events
      description: "Upset multiple Marketing Event. If there is an existing Marketing\
        \ event with the specified id, it will be updated; otherwise a new event will\
        \ be created."
      operationId: post-/marketing/v3/marketing-events/events/upsert
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/{externalEventId}:
    get:
      tags:
      - Basic
      summary: Get a marketing event
      description: "Returns the details of the Marketing Event with the specified\
        \ id, if one exists."
      operationId: "get-/marketing/v3/marketing-events/events/{externalEventId}"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.read
    put:
      tags:
      - Basic
      summary: Create or update a marketing event
      description: "Upsets a Marketing Event. If there is an existing Marketing event\
        \ with the specified id, it will be updated; otherwise a new event will be\
        \ created."
      operationId: "put-/marketing/v3/marketing-events/events/{externalEventId}"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
    delete:
      tags:
      - Basic
      summary: Delete a marketing event
      description: "Deletes an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: "delete-/marketing/v3/marketing-events/events/{externalEventId}"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
    patch:
      tags:
      - Basic
      summary: Update a marketing event
      description: "Updates an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: "patch-/marketing/v3/marketing-events/events/{externalEventId}"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      tags:
      - Basic
      summary: Mark a marketing event as cancelled
      description: Mark a marketing event as cancelled.
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      tags:
      - Subscriber State Changes
      summary: Record
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses."
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      tags:
      - Subscriber State Changes
      summary: Record
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids."
      operationId: "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert"
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      tags:
      - Settings
      summary: Retrieve the application settings
      description: Retrieve the current settings for the application.
      operationId: "get-/marketing/v3/marketing-events/{appId}/settings"
      security:
      - hapikey: []
      - developer_hapikey: []
    post:
      tags:
      - Settings
      summary: Update the application settings
      description: Create or update the current settings for the application.
      operationId: "post-/marketing/v3/marketing-events/{appId}/settings"
      security:
      - hapikey: []
      - developer_hapikey: []
components:
  securitySchemes:
    oauth2_legacy:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            crm.objects.marketing_events.write: Write marketing events
            crm.objects.marketing_events.read: Read marketing events
    hapikey:
      type: apiKey
      name: hapikey
      in: query
    developer_hapikey:
      type: apiKey
      name: hapikey
      in: query
