openapi: 3.0.1
info:
  description: |-
    CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.

    ## Supported Object Types

    This API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by exploring the [CRM Object Properties API](https://developers.hubspot.com/docs/methods/crm-properties/crm-properties-overview).

    |Object Type |Properties returned by default |
    |--|--|
    | `companies` | `name`, `domain` |
    | `contacts` | `firstname`, `lastname`, `email` |
    | `deals` | `dealname`, `amount`, `closedate`, `pipeline`, `dealstage` |
    | `products` | `name`, `description`, `price` |
    | `tickets` | `content`, `hs_pipeline`, `hs_pipeline_stage`, `hs_ticket_category`, `hs_ticket_priority`, `subject` |

    Find a list of all properties for an object type using the [CRM Object Properties](https://developers.hubspot.com/docs/methods/crm-properties/get-properties) API. e.g. `GET https://api.hubapi.com/properties/v2/companies/properties`. Change the properties returned in the response using the `properties` array in the request body.
  title: CRM Objects
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Associations
- name: Basic
- name: Batch
- name: GDPR
- name: Search
- name: Public_Object
paths:
  /crm/v3/objects/{objectType}:
    get:
      description: Read a page of objects. Control what is returned via the `properties`
        query param.
      operationId: GetPage
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: List
      tags:
      - Basic
    post:
      description: "Create a CRM object with the given properties and return a copy\
        \ of the object, including the ID. Documentation and examples for creating\
        \ standard objects is provided."
      operationId: Create
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/{objectType}/batch/archive:
    post:
      operationId: BatchArchive
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Archive a batch of objects by ID
      tags:
      - Batch
  /crm/v3/objects/{objectType}/batch/create:
    post:
      operationId: BatchCreate
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Create a batch of objects
      tags:
      - Batch
  /crm/v3/objects/{objectType}/batch/read:
    post:
      operationId: BatchRead
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: "Read a batch of objects by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/{objectType}/batch/update:
    post:
      operationId: BatchUpdate
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Update a batch of objects
      tags:
      - Batch
  /crm/v3/objects/{objectType}/gdpr-delete:
    post:
      description: "Permanently delete a contact and all associated content to follow\
        \ GDPR. Use optional property 'idProperty' set to 'email' to identify contact\
        \ by email address. If email address is not found, the email address will\
        \ be added to a blocklist and prevent it from being used in the future."
      operationId: Delete
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: GDPR DELETE
      tags:
      - GDPR
  /crm/v3/objects/{objectType}/merge:
    post:
      operationId: Merge
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Merge two objects with same type
      tags:
      - Public_Object
  /crm/v3/objects/{objectType}/search:
    post:
      operationId: Search
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v3/objects/{objectType}/{objectId}:
    delete:
      description: "Move an Object identified by `{objectId}` to the recycling bin."
      operationId: Archive
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{objectId}`. `{objectId}` refers\
        \ to the internal object ID by default, or optionally any unique property\
        \ value as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: GetByID
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{objectId}`.\
        \ `{objectId}` refers to the internal object ID by default, or optionally\
        \ any unique property value as specified by the `idProperty` query param.\
        \ Provided property values will be overwritten. Read-only and non-existent\
        \ properties will be ignored. Properties values can be cleared by passing\
        \ an empty string."
      operationId: Update
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/{objectType}/{objectId}/associations/{toObjectType}:
    get:
      operationId: AssociationsGetAll
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: List associations of an object by type
      tags:
      - Associations
  /crm/v3/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}/{associationType}:
    delete:
      operationId: AssociationsArchive
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Remove an association between two objects
      tags:
      - Associations
    put:
      operationId: AssociationsCreate
      security:
      - oauth2:
        - crm.objects.quotes.write
      - oauth2_legacy:
        - tickets
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Associate an object with another object
      tags:
      - Associations
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.custom.read: View custom object records
            tickets: Read and write tickets
            media_bridge.read: Read media and media events
            contacts: Read from and write to my Contacts
            crm.objects.custom.write: Change custom object records
            e-commerce: e-commerce
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.companies.write: ' '
            crm.objects.companies.read: ' '
            crm.objects.line_items.write: Line Items
            crm.objects.quotes.read: Quotes
            crm.objects.deals.write: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.deals.read: ' '
            crm.objects.quotes.write: Quotes
            crm.objects.contacts.read: ' '
            crm.objects.contacts.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
