openapi: 3.0.1
info:
  title: Quotes
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Associations
- name: Basic
- name: Batch
- name: Search
- name: Public_Object
paths:
  /crm/v3/objects/quotes:
    get:
      description: Read a page of quotes. Control what is returned via the `properties`
        query param.
      operationId: GetPage
      security:
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      summary: List
      tags:
      - Basic
    post:
      description: "Create a quote with the given properties and return a copy of\
        \ the object, including the ID. Documentation and examples for creating standard\
        \ quotes is provided."
      operationId: Create
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/quotes/batch/archive:
    post:
      operationId: BatchArchive
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Archive a batch of quotes by ID
      tags:
      - Batch
  /crm/v3/objects/quotes/batch/create:
    post:
      operationId: BatchCreate
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Create a batch of quotes
      tags:
      - Batch
  /crm/v3/objects/quotes/batch/read:
    post:
      operationId: BatchRead
      security:
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      summary: "Read a batch of quotes by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/quotes/batch/update:
    post:
      operationId: BatchUpdate
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Update a batch of quotes
      tags:
      - Batch
  /crm/v3/objects/quotes/merge:
    post:
      operationId: Merge
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Merge two quotes with same type
      tags:
      - Public_Object
  /crm/v3/objects/quotes/search:
    post:
      operationId: Search
      security:
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v3/objects/quotes/{quoteId}:
    delete:
      description: "Move an Object identified by `{quoteId}` to the recycling bin."
      operationId: Archive
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{quoteId}`. `{quoteId}` refers to\
        \ the internal object ID by default, or optionally any unique property value\
        \ as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: GetByID
      security:
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{quoteId}`.\
        \ `{quoteId}` refers to the internal object ID by default, or optionally any\
        \ unique property value as specified by the `idProperty` query param. Provided\
        \ property values will be overwritten. Read-only and non-existent properties\
        \ will be ignored. Properties values can be cleared by passing an empty string."
      operationId: Update
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/quotes/{quoteId}/associations/{toObjectType}:
    get:
      operationId: AssociationsGetAll
      security:
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.quotes.read
      summary: List associations of a quote by type
      tags:
      - Associations
  /crm/v3/objects/quotes/{quoteId}/associations/{toObjectType}/{toObjectId}/{associationType}:
    delete:
      operationId: AssociationsArchive
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Remove an association between two quotes
      tags:
      - Associations
    put:
      operationId: AssociationsCreate
      security:
      - oauth2:
        - crm.objects.quotes.write
      - hapikey: []
      - oauth2_legacy:
        - e-commerce
      summary: Associate a quote with another object
      tags:
      - Associations
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            e-commerce: e-commerce
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.quotes.read: Quotes
            crm.objects.quotes.write: Quotes
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
