openapi: 3.0.1
info:
  description: Associations define the relationships between objects in HubSpot. These
    endpoints allow you to create, read, and remove associations.
  title: Associations
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Batch
- name: Types
paths:
  /crm/v3/associations/{fromObjectType}/{toObjectType}/batch/archive:
    post:
      description: Remove the associations between all pairs of objects identified
        in the request body.
      operationId: post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/archive_archive
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Archive a batch of associations
      tags:
      - Batch
  /crm/v3/associations/{fromObjectType}/{toObjectType}/batch/create:
    post:
      description: Associate all pairs of objects identified in the request body.
      operationId: post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/create_create
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Create a batch of associations
      tags:
      - Batch
  /crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read:
    post:
      description: Get the IDs of all `{toObjectType}` objects associated with those
        specified in the request body.
      operationId: post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read_read
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: Read a batch of associations
      tags:
      - Batch
  /crm/v3/associations/{fromObjectType}/{toObjectType}/types:
    get:
      description: List all the valid association types available between two object
        types
      operationId: get-/crm/v3/associations/{fromObjectType}/{toObjectType}/types_getAll
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - contacts
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.companies.write
      summary: List association types
      tags:
      - Types
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            e-commerce: e-commerce
            crm.objects.custom.write: Change custom object records
            contacts: Read from and write to my Contacts
            media_bridge.read: Read media and media events
            tickets: Read and write tickets
            crm.objects.custom.read: View custom object records
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.deals.write: ' '
            crm.objects.deals.read: ' '
            crm.objects.contacts.read: ' '
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.objects.contacts.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
