openapi: 3.0.1
info:
  description: "The CRM uses schemas to define how custom objects should store and\
    \ represent information in the HubSpot CRM. Schemas define details about an object's\
    \ type, properties, and associations. The schema can be uniquely identified by\
    \ its **object type ID**."
  title: Schemas
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: Create a new object for storing information about cars at
    a car dealership. Your object definition could include properties to store information
    as well as the filters available on the custom object index page.
  x-hubspot-related-documentation:
  - name: Custom Object Guide
    url: https://hubspot.dev/guides/api/crm/crm-custom-objects
  x-hubspot-introduction: "Use the custom objects schema API to define new types of\
    \ CRM records in your account. After setting up an object schema, you'll then\
    \ be able to create custom records under that object both in HubSpot and using\
    \ the custom object records API."
servers:
- url: https://api.hubapi.com
tags:
- name: Core
- name: Public_Object_Schemas
paths:
  /crm/v3/schemas/{objectType}:
    delete:
      description: Deletes a schema. Any existing records of this schema must be deleted
        **first**. Otherwise this call will fail.
      operationId: "delete-/crm/v3/schemas/{objectType}_archive"
      security:
      - private_apps_legacy:
        - crm.schemas.custom.write
      summary: Delete a schema
      tags:
      - Core
    get:
      description: Returns an existing object schema.
      operationId: "get-/crm/v3/schemas/{objectType}_getById"
      security:
      - private_apps_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      summary: Get an existing schema
      tags:
      - Core
    patch:
      description: Update the details for an existing object schema.
      operationId: "patch-/crm/v3/schemas/{objectType}_update"
      security:
      - private_apps_legacy:
        - crm.schemas.custom.write
        - crm.objects.custom.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      summary: Update a schema
      tags:
      - Core
  /crm/v3/schemas/{objectType}/associations:
    post:
      description: Defines a new association between the primary schema's object type
        and other object types.
      operationId: "post-/crm/v3/schemas/{objectType}/associations_createAssociation"
      security:
      - private_apps_legacy:
        - crm.schemas.custom.write
        - crm.objects.custom.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      summary: Create an association
      tags:
      - Core
  /crm/v3/schemas/{objectType}/purge:
    delete:
      deprecated: true
      operationId: "delete-/crm/v3/schemas/{objectType}/purge_purge"
      security:
      - private_apps_legacy:
        - crm.schemas.custom.write
      tags:
      - Public_Object_Schemas
  /crm/v3/schemas/{objectType}/associations/{associationIdentifier}:
    delete:
      description: Removes an existing association from a schema.
      operationId: "delete-/crm/v3/schemas/{objectType}/associations/{associationIdentifier}_archiveAssociation"
      security:
      - private_apps_legacy:
        - crm.schemas.custom.write
      summary: Remove an association
      tags:
      - Core
  /crm/v3/schemas:
    get:
      description: Returns all object schemas that have been defined for your account.
      operationId: get-/crm/v3/schemas_getAll
      security:
      - private_apps_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      summary: Get all schemas
      tags:
      - Core
    post:
      description: "Define a new object schema, along with custom properties and associations.\
        \ The entire object schema, including its object type ID, properties, and\
        \ associations will be returned in the response."
      operationId: post-/crm/v3/schemas_create
      security:
      - private_apps_legacy:
        - crm.schemas.custom.write
        - crm.objects.custom.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      summary: Create a new schema
      tags:
      - Core
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.schemas.custom.read: View custom object definitions
            crm.objects.custom.read: View custom object records
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
