openapi: 3.0.1
info:
  description: "These APIs allow you to interact with HubSpot's Marketing Events Extension.\
    \ It allows you to:\n* Create, Read or update Marketing Event information in HubSpot\n\
    * Specify whether a HubSpot contact has registered, attended or cancelled a registration\
    \ to a Marketing Event.\n* Specify a URL that can be called to get the details\
    \ of a Marketing Event.\n"
  title: Marketing Events Extension
  version: v3
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Attendance Subscriber State Changes
- name: Subscriber State Changes
- name: Marketing_Events_External
- name: Basic
- name: Settings
- name: Search
paths:
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids."
      operationId: AttendanceCreate_create
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Attendance Subscriber State Changes
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids. Note that the contact\
        \ must already exist in HubSpot; a contact will not be create."
      operationId: ExternalUpsertByID
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Subscriber State Changes
  /marketing/v3/marketing-events/events/delete:
    post:
      description: Bulk delete a number of marketing events in HubSpot
      operationId: ArchiveBatch
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Delete multiple marketing events
      tags:
      - Batch
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      description: Mark a marketing event as cancelled.
      operationId: ExternalCancel
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Mark a marketing event as cancelled
      tags:
      - Basic
  /marketing/v3/marketing-events/events/{externalEventId}:
    delete:
      description: "Deletes an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: ExternalArchive
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Delete a marketing event
      tags:
      - Basic
    get:
      description: "Returns the details of the Marketing Event with the specified\
        \ id, if one exists."
      operationId: ExternalGetByID
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy:
        - crm.objects.marketing_events.read
      summary: Get a marketing event
      tags:
      - Basic
    patch:
      description: "Updates an existing Marketing Event with the specified id, if\
        \ one exists."
      operationId: ExternalUpdate
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Update a marketing event
      tags:
      - Basic
    put:
      description: "Upsets a Marketing Event. If there is an existing Marketing event\
        \ with the specified id, it will be updated; otherwise a new event will be\
        \ created."
      operationId: ExternalReplace
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create or update a marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/events/upsert:
    post:
      description: "Upset multiple Marketing Event. If there is an existing Marketing\
        \ event with the specified id, it will be updated; otherwise a new event will\
        \ be created."
      operationId: Upsert
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create or update multiple marketing events
      tags:
      - Batch
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses. Note that the contact\
        \ must already exist in HubSpot; a contact will not be created."
      operationId: ExternalEmailUpsertByID
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Subscriber State Changes
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses. If contact is not\
        \ present it will be automatically created."
      operationId: AttendanceEmailCreate_createByEmail
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Attendance Subscriber State Changes
  /marketing/v3/marketing-events/events/{externalEventId}/complete:
    post:
      operationId: ExternalComplete_complete
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events:
    post:
      description: Creates a new marketing event in HubSpot
      operationId: Create
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Create a marketing event
      tags:
      - Basic
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      description: Retrieve the current settings for the application.
      operationId: SettingsGetAll
      security:
      - developer_hapikey: []
      summary: Retrieve the application settings
      tags:
      - Settings
    post:
      description: Create or update the current settings for the application.
      operationId: SettingsCreate
      security:
      - developer_hapikey: []
      summary: Update the application settings
      tags:
      - Settings
  /marketing/v3/marketing-events/events/search:
    get:
      description: Search for marketing events that have an event id that starts with
        the query string
      operationId: Search
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy:
        - crm.objects.marketing_events.read
      summary: Search for marketing events
      tags:
      - Search
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.write: Write marketing events
            crm.objects.marketing_events.read: Read marketing events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
