openapi: 3.0.1
info:
  description: |
    These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to:
    * Create, Read or update Marketing Event information in HubSpot
    * Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event.
    * Specify a URL that can be called to get the details of a Marketing Event.
  title: Marketing Events Extension
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- description: "Operations to mark HubSpot contacts as registered, attended or cancelled\
    \ a registration to a Marketing Event."
  name: Attendance Subscriber State Changes
- name: Marketing_Events_External
- name: Settings_External
paths:
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using HubSpot contact ids."
      operationId: AttendanceCreate
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Attendance Subscriber State Changes
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create:
    post:
      description: "Record a subscription state between multiple HubSpot contacts\
        \ and a marketing event, using contact email addresses. If contact is not\
        \ present it will be automatically created. If you set params "
      operationId: AttendanceEmailCreate
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      summary: Record
      tags:
      - Attendance Subscriber State Changes
  /marketing/v3/marketing-events/events:
    post:
      operationId: Create
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/delete:
    post:
      operationId: Archive
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/search:
    get:
      operationId: Search
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/upsert:
    post:
      operationId: Upsert
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/{externalEventId}:
    delete:
      operationId: ExternalArchive
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
    get:
      operationId: ExternalGetByID
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      tags:
      - Marketing_Events_External
    patch:
      operationId: ExternalUpdate
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
    put:
      operationId: ExternalReplace
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      operationId: ExternalCancel
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/{externalEventId}/complete:
    post:
      operationId: ExternalComplete
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      operationId: ExternalEmailUpsertByID
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      operationId: ExternalUpsertByID
      security:
      - hapikey: []
      - oauth2_legacy:
        - crm.objects.marketing_events.write
      tags:
      - Marketing_Events_External
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      operationId: SettingsGetAll
      security:
      - hapikey: []
      - developer_hapikey: []
      tags:
      - Settings_External
    post:
      operationId: SettingsCreate
      security:
      - hapikey: []
      - developer_hapikey: []
      tags:
      - Settings_External
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.write: Write marketing events
            crm.objects.marketing_events.read: Read marketing events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
