openapi: 3.0.1
info:
  description: All HubSpot objects store data in default and custom properties. These
    endpoints provide access to read and modify object properties in HubSpot.
  title: Properties
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: Create a set of new custom multi-select properties for storing
    contract data on company records.
  x-hubspot-related-documentation:
  - name: Properties Guide
    url: https://hubspot.dev/guides/api/crm/properties
  x-hubspot-introduction: "Use the properties API to store information in fields on\
    \ individual contact records. You can use this API to manage existing default\
    \ and custom properties, create new custom properties, and more."
servers:
- url: https://api.hubapi.com
tags:
- description: ""
  name: Batch
  x-hubspot-tag-name-english-source: Batch
- description: ""
  name: Groups
  x-hubspot-tag-name-english-source: Groups
- description: ""
  name: Core
  x-hubspot-tag-name-english-source: Core
paths:
  /crm/v3/properties/{objectType}/batch/archive:
    post:
      description: "Archive a provided list of properties. This method will return\
        \ a 204 No Content response on success regardless of the initial state of\
        \ the property (e.g. active, already archived, non-existent)."
      operationId: BatchArchive
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Archive a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/groups/{groupName}:
    delete:
      description: "Move a property group identified by {groupName} to the recycling\
        \ bin."
      operationId: GroupsArchive
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Archive a property group
      tags:
      - Groups
    get:
      description: "Read a property group identified by {groupName}."
      operationId: GroupsGetByName
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Read a property group
      tags:
      - Groups
    patch:
      description: "Perform a partial update of a property group identified by {groupName}.\
        \ Provided fields will be overwritten."
      operationId: GroupsUpdate
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a property group
      tags:
      - Groups
  /crm/v3/properties/{objectType}/{propertyName}:
    delete:
      description: "Move a property identified by {propertyName} to the recycling\
        \ bin."
      operationId: Archive
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Archive a property
      tags:
      - Core
    get:
      description: "Read a property identified by {propertyName}."
      operationId: GetByName
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Read a property
      tags:
      - Core
    patch:
      description: "Perform a partial update of a property identified by {propertyName}.\
        \ Provided fields will be overwritten."
      operationId: Update
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Update a property
      tags:
      - Core
  /crm/v3/properties/{objectType}/batch/read:
    post:
      description: Read a provided list of properties.
      operationId: BatchRead
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Read a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}/batch/create:
    post:
      description: Create a batch of properties using the same rules as when creating
        an individual property.
      operationId: BatchCreate
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a batch of properties
      tags:
      - Batch
  /crm/v3/properties/{objectType}:
    get:
      description: Read all existing properties for the specified object type and
        HubSpot account.
      operationId: GetAll
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Read all properties
      tags:
      - Core
    post:
      description: Create and return a copy of a new property for the specified object
        type.
      operationId: Create
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a property
      tags:
      - Core
  /crm/v3/properties/{objectType}/groups:
    get:
      description: Read all existing property groups for the specified object type
        and HubSpot account.
      operationId: GroupsGetAll
      security:
      - oauth2_legacy:
        - media_bridge.read
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - private_apps:
        - crm.objects.companies.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.quotes.read
      - private_apps:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.schemas.custom.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.schemas.line_items.read
      - oauth2:
        - crm.schemas.line_items.read
      summary: Read all property groups
      tags:
      - Groups
    post:
      description: Create and return a copy of a new property group.
      operationId: GroupsCreate
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps:
        - crm.schemas.deals.write
      summary: Create a property group
      tags:
      - Groups
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.goals.read: Read goals
            tickets: Read and write tickets
            crm.schemas.custom.read: View custom object definitions
            timeline: Create timeline events
            e-commerce: e-commerce
            media_bridge.read: Read media and media events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.contacts.read: ' '
            crm.schemas.deals.read: ' '
            crm.objects.deals.write: ' '
            crm.schemas.line_items.read: Line Items schemas
            crm.objects.deals.read: ' '
            crm.schemas.companies.read: ' '
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.schemas.contacts.read: ' '
            crm.objects.contacts.write: ' '
            crm.schemas.quotes.read: Quotes schemas
            crm.schemas.companies.write: ' '
            crm.schemas.contacts.write: ' '
            crm.schemas.deals.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
x-hubspot-documentation-banner: NONE
