openapi: 3.0.1
info:
  description: "This feature allows an app to create and configure custom events that\
    \ can show up in the timelines of certain CRM objects like contacts, companies,\
    \ tickets, or deals. You'll find multiple use cases for this API in the sections\
    \ below."
  title: Timeline events
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- description: Definitions and configuration for timeline events.
  name: Templates
- description: Specific tokens that map to CRM properties and can be used by timeline
    events. This is how you can use property stamping to create full CRM objects.
  name: Tokens
- description: Events shown on a CRM object's timeline.
  name: Events
paths:
  /crm/v3/timeline/events:
    post:
      description: "Creates an instance of a timeline event based on an event template.\
        \ Once created, this event is immutable on the object timeline and cannot\
        \ be modified. If the event template was configured to update object properties\
        \ via `objectPropertyName`, this call will also attempt to updates those properties,\
        \ or add them if they don't exist."
      operationId: Create
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - timeline
      - private_apps:
        - crm.objects.companies.write
      - private_apps:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.companies.write
      summary: Create a single event
      tags:
      - Events
  /crm/v3/timeline/events/batch/create:
    post:
      description: "Creates multiple instances of timeline events based on an event\
        \ template. Once created, these event are immutable on the object timeline\
        \ and cannot be modified. If the event template was configured to update object\
        \ properties via `objectPropertyName`, this call will also attempt to updates\
        \ those properties, or add them if they don't exist."
      operationId: BatchCreate
      security:
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - timeline
      - private_apps:
        - crm.objects.companies.write
      - private_apps:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.companies.write
      summary: Creates multiple events
      tags:
      - Events
  /crm/v3/timeline/events/{eventTemplateId}/{eventId}:
    get:
      description: "This returns the previously created event. It contains all existing\
        \ info for the event, but not necessarily the CRM object."
      operationId: GetByID
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      summary: Gets the event
      tags:
      - Events
  /crm/v3/timeline/events/{eventTemplateId}/{eventId}/detail:
    get:
      description: "This will take the `detailTemplate` from the event template and\
        \ return an object rendering the specified event. If the template references\
        \ `extraData` that isn't found in the event, it will be ignored and we'll\
        \ render without it."
      operationId: GetDetailByID
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      summary: Gets the detailTemplate as rendered
      tags:
      - Events
  /crm/v3/timeline/events/{eventTemplateId}/{eventId}/render:
    get:
      description: "This will take either the `headerTemplate` or `detailTemplate`\
        \ from the event template and render for the specified event as HTML. If the\
        \ template references `extraData` that isn't found in the event, it will be\
        \ ignored and we'll render without it."
      operationId: GetRenderByID
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - private_apps:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps_legacy:
        - timeline
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps:
        - crm.schemas.companies.read
      - oauth2:
        - crm.schemas.companies.read
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.read
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - timeline
      summary: Renders the header or detail as HTML
      tags:
      - Events
  /crm/v3/timeline/{appId}/event-templates:
    get:
      description: Use this to list all event templates owned by your app.
      operationId: TemplateGetAll
      security:
      - developer_hapikey: []
      summary: List all event templates for your app
      tags:
      - Templates
    post:
      description: "Event templates define the general structure for a custom timeline\
        \ event. This includes formatted copy for its heading and details, as well\
        \ as any custom property definitions. The event could be something like viewing\
        \ a video, registering for a webinar, or filling out a survey. A single app\
        \ can define multiple event templates.\n\nEvent templates will be created\
        \ for contacts by default, but they can be created for companies, tickets,\
        \ and deals as well.\n\nEach event template contains its own set of tokens\
        \ and `Markdown` templates. These tokens can be associated with any CRM object\
        \ properties via the `objectPropertyName` field to fully build out CRM objects.\n\
        \nYou must create an event template before you can create events."
      operationId: TemplateCreate
      security:
      - developer_hapikey: []
      summary: Create an event template for your app
      tags:
      - Templates
  /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}:
    delete:
      description: "This will delete the event template. All associated events will\
        \ be removed from search results and the timeline UI.\n\nThis action can't\
        \ be undone, so it's highly recommended that you stop using any associated\
        \ events before deleting a template."
      operationId: TemplatesArchive
      security:
      - developer_hapikey: []
      summary: Deletes an event template for the app
      tags:
      - Templates
    get:
      description: View the current state of a specific template and its tokens.
      operationId: TemplatesGetByID
      security:
      - developer_hapikey: []
      summary: Gets a specific event template for your app
      tags:
      - Templates
    put:
      description: "Updates an existing template and its tokens. This is primarily\
        \ used to update the headerTemplate/detailTemplate, and those changes will\
        \ take effect for existing events.\n\nYou can also update or replace all the\
        \ tokens in the template here instead of doing individual API calls on the\
        \ `/tokens` endpoint."
      operationId: TemplatesUpdate
      security:
      - developer_hapikey: []
      summary: Update an existing event template
      tags:
      - Templates
  /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens:
    post:
      description: "Once you've defined an event template, it's likely that you'll\
        \ want to define tokens for it as well. You can do this on the event template\
        \ itself or update individual tokens here.\n\nEvent type tokens allow you\
        \ to attach custom data to events displayed in a timeline or used for list\
        \ segmentation.\n\nYou can also use `objectPropertyName` to associate any\
        \ CRM object properties. This will allow you to fully build out CRM objects.\n\
        \nToken names should be unique across the template."
      operationId: TemplatesTokensCreate
      security:
      - developer_hapikey: []
      summary: Adds a token to an existing event template
      tags:
      - Tokens
  /crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}:
    delete:
      description: "This will remove the token from an existing template. Existing\
        \ events and CRM objects will still retain the token and its mapped object\
        \ properties, but new ones will not.\n\nThe timeline will still display this\
        \ property for older CRM objects if it's still referenced in the template\
        \ `Markdown`. New events will not.\n\nAny lists or reports referencing deleted\
        \ tokens will no longer return new contacts, but old ones will still exist\
        \ in the lists."
      operationId: TemplatesTokensArchive
      security:
      - developer_hapikey: []
      summary: Removes a token from the event template
      tags:
      - Tokens
    put:
      description: This will update the existing token on an event template. Name
        and type can't be changed on existing tokens.
      operationId: TemplatesTokensUpdate
      security:
      - developer_hapikey: []
      summary: Updates an existing token on an event template
      tags:
      - Tokens
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            tickets: Read and write tickets
            timeline: Create timeline events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.schemas.contacts.write: ' '
            crm.objects.contacts.write: ' '
            crm.schemas.companies.write: ' '
            crm.objects.companies.write: ' '
            crm.objects.deals.write: ' '
            crm.schemas.deals.write: ' '
            crm.objects.contacts.read: ' '
            crm.schemas.contacts.read: ' '
            crm.schemas.companies.read: ' '
            crm.objects.companies.read: ' '
            crm.objects.deals.read: ' '
            crm.schemas.deals.read: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
