openapi: 3.0.1
info:
  description: "Pipelines represent distinct stages in a workflow, like closing a\
    \ deal or servicing a support ticket. These endpoints provide access to read and\
    \ modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object\
    \ types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId\
    \ as a parameter, that ID must correspond to an existing, un-archived pipeline.\
    \ Otherwise the request will fail with a `404 Not Found` response."
  title: CRM Pipelines
  version: v3
servers:
- url: https://api.hubapi.com/
tags:
- name: Pipeline Stages
- name: Pipelines
- name: Pipeline Audits
- name: Pipeline Stage Audits
paths:
  /crm/v3/pipelines/{objectType}:
    get:
      description: "Return all pipelines for the object type specified by `{objectType}`."
      operationId: "get-/crm/v3/pipelines/{objectType}_getAll"
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - timeline
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.line_items.read
      summary: Retrieve all pipelines
      tags:
      - Pipelines
    post:
      description: "Create a new pipeline with the provided property values. The entire\
        \ pipeline object, including its unique ID, will be returned in the response."
      operationId: "post-/crm/v3/pipelines/{objectType}_create"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Create a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}:
    delete:
      description: "Delete the pipeline identified by `{pipelineId}`."
      operationId: "delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Delete a pipeline
      tags:
      - Pipelines
    get:
      description: "Return a single pipeline object identified by its unique `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById"
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - timeline
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return a pipeline by ID
      tags:
      - Pipelines
    patch:
      description: "Perform a partial update of the pipeline identified by `{pipelineId}`.\
        \ The updated pipeline will be returned in the response."
      operationId: "patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Update a pipeline
      tags:
      - Pipelines
    put:
      description: Replace all the properties of an existing pipeline with the values
        provided. This will overwrite any existing pipeline stages. The updated pipeline
        will be returned in the response.
      operationId: "put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Replace a pipeline
      tags:
      - Pipelines
  /crm/v3/pipelines/{objectType}/{pipelineId}/audit:
    get:
      description: "Return a reverse chronological list of all mutations that have\
        \ occurred on the pipeline identified by `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit"
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - timeline
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return an audit of all changes to the pipeline
      tags:
      - Pipeline Audits
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages:
    get:
      description: "Return all the stages associated with the pipeline identified\
        \ by `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll"
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - timeline
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return all stages of a pipeline
      tags:
      - Pipeline Stages
    post:
      description: "Create a new stage associated with the pipeline identified by\
        \ `{pipelineId}`. The entire stage object, including its unique ID, will be\
        \ returned in the response."
      operationId: "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Create a pipeline stage
      tags:
      - Pipeline Stages
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}:
    delete:
      description: "Delete the pipeline stage identified by `{stageId}` associated\
        \ with the pipeline identified by `{pipelineId}`."
      operationId: "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Delete a pipeline stage
      tags:
      - Pipeline Stages
    get:
      description: "Return the stage identified by `{stageId}` associated with the\
        \ pipeline identified by `{pipelineId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById"
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - timeline
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return a pipeline stage by ID
      tags:
      - Pipeline Stages
    patch:
      description: "Perform a partial update of the pipeline stage identified by `{stageId}`\
        \ associated with the pipeline identified by `{pipelineId}`. Any properties\
        \ not included in this update will keep their existing values. The updated\
        \ stage will be returned in the response."
      operationId: "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Update a pipeline stage
      tags:
      - Pipeline Stages
    put:
      description: Replace all the properties of an existing pipeline stage with the
        values provided. The updated stage will be returned in the response.
      operationId: "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace"
      security:
      - oauth2_legacy:
        - tickets
      - hapikey: []
      - oauth2:
        - crm.schemas.deals.write
      - oauth2_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.companies.write
      - oauth2_legacy:
        - contacts
      summary: Replace a pipeline stage
      tags:
      - Pipeline Stages
  /crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit:
    get:
      description: "Return a reverse chronological list of all mutations that have\
        \ occurred on the pipeline stage identified by `{stageId}`."
      operationId: "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit"
      security:
      - oauth2:
        - crm.schemas.contacts.read
      - oauth2_legacy:
        - media_bridge.read
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.objects.contacts.read
      - hapikey: []
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.deals.read
      - oauth2_legacy:
        - crm.schemas.custom.read
      - oauth2:
        - crm.schemas.quotes.read
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.companies.read
      - oauth2_legacy:
        - e-commerce
      - oauth2_legacy:
        - timeline
      - oauth2:
        - crm.schemas.deals.read
      - oauth2_legacy:
        - contacts
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.line_items.read
      summary: Return an audit of all changes to the pipeline stage
      tags:
      - Pipeline Stage Audits
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            e-commerce: e-commerce
            contacts: Read from and write to my Contacts
            media_bridge.read: Read media and media events
            tickets: Read and write tickets
            crm.schemas.custom.read: View custom object definitions
            timeline: Create timeline events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.companies.read: ' '
            crm.objects.companies.write: ' '
            crm.schemas.contacts.read: ' '
            crm.objects.contacts.write: ' '
            crm.schemas.quotes.read: Quotes schemas
            crm.objects.contacts.read: ' '
            crm.schemas.deals.read: ' '
            crm.objects.deals.write: ' '
            crm.schemas.line_items.read: Line Items schemas
            crm.objects.deals.read: ' '
            crm.schemas.companies.read: ' '
            crm.schemas.contacts.write: ' '
            crm.schemas.deals.write: ' '
            crm.schemas.companies.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
x-hubspot-available-client-libraries:
- PHP
- Node
- Python
- Ruby
